name: homelab
services:
  caddy:
    image: homelab-caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    secrets:
      - cloudflare_api_token
    volumes:
      - ./services/caddy/conf:/etc/caddy
      # I don't have any static content, but if I did, this is where I'd put it.
      # - ./services/caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - ddclient

  ddclient:
    image: lscr.io/linuxserver/ddclient:4.0.0
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - FILE__CLOUDFLARE_API_TOKEN=/run/secrets/cloudflare_api_token
    secrets:
      - cloudflare_api_token
    volumes:
      - ./services/ddclient:/config
    restart: unless-stopped

  couchdb:
    image: couchdb:3.5
    restart: unless-stopped
    secrets:
      - couchdb_user
      - couchdb_password
    entrypoint: |
      sh -c '
        export COUCHDB_USER=$$(cat /run/secrets/couchdb_user)
        export COUCHDB_PASSWORD=$$(cat /run/secrets/couchdb_password)
        exec /docker-entrypoint.sh "$$@"
      ' --
    command: ["couchdb"]
    volumes:
      - ./services/couchdb/data:/opt/couchdb/data
      - ./services/couchdb/etc:/opt/couchdb/etc/local.d

volumes:
  caddy_data:
  caddy_config:

secrets:
  cloudflare_api_token:
    file: ./secrets/cloudflare_api_token.txt
  couchdb_user:
    file: ./secrets/couchdb_user.txt
  couchdb_password:
    file: ./secrets/couchdb_password.txt
